### ISSUE TITLE
Roadmap for '@gltf-transform/view' package

### ISSUE THREAD

**Issue by donmccurdy** [donmccurdy/glTF-Transform#1400]
I've moved `@gltf-transform/view` from the separate repository (https://github.com/donmccurdy/glTF-Transform-View) where it was incubated, into this monorepo. This issue is intended to track its missing features.

### Geometry

- [x] SkinnedMesh
- [ ] triangle fan
- [ ] triangle strip

### Animation

Currently the bindings ignore animation. Proposed API:

```javascript
const documentView = new DocumentView(document);
const animationDef = document.getRoot().listAnimations()[0];
const animation = documentView.view(animationDef); // THREE.AnimationClip
```

Will need to decide how to handle keyframe targeting. By name, with a workaround for duplicate names? By UUID, with some way of knowing UUID won't change in update cycle?

Draft:

- https://github.com/donmccurdy/glTF-Transform-View/pull/76

### Extensions

**P0:**

- [x] KHR_draco_mesh_compression
- [x] KHR_mesh_quantization
- [x] KHR_materials_clearcoat
- [x] KHR_materials_ior
- [x] KHR_materials_sheen
- [x] KHR_materials_specular
- [x] KHR_materials_transmission
- [x] KHR_materials_volume
- [x] KHR_materials_unlit
- [x] KHR_texture_basisu
- [x] KHR_texture_transform
- [x] EXT_meshopt_compression
- [x] EXT_texture_webp
 
**P1:**

- [x] KHR_lights_punctual
- [x] KHR_materials_emissive_strength

**P2:**

- [x] KHR_materials_iridescence
- [ ] KHR_materials_variants
- [x] EXT_mesh_gpu_instancing

**Out of scope:**

- [x] ~~KHR_materials_pbrSpecularGlossiness~~
