### ISSUE TITLE
Broken animation after resampling

### ISSUE THREAD

**Issue by donmccurdy** [donmccurdy/glTF-Transform#501]
**Describe the bug**

After resampling, the animation sequence in this example is broken.

**To Reproduce**

[Archive.zip](https://github.com/donmccurdy/glTF-Transform/files/8081046/Archive.zip)

1. `gltf-transform resample Arm.glb Arm-resampled.glb`

Decreasing tolerance will fix the issue, but also prevents resampling from reducing the size very much. My hunch is that the [current implementation of `resample()](https://github.com/donmccurdy/glTF-Transform/blob/ca18796/packages/functions/src/resample.ts#L72-L142) does not handle quaternion keyframe tracks properly.

**Expected behavior**

Animation should appear visually identical, within some small tolerance.

**Related**

- https://github.com/donmccurdy/glTF-Transform/pull/492
- https://github.com/donmccurdy/glTF-Transform/issues/489

**Sub-issues:**

- [ ] `resample()` should remove channels that have no effect
- [x] `resample()` must slerp, not lerp, quaternion tracks
- [x] `resample()` must not collapse keyframes A-B-C if A and C are >180º apart

**Comment by donmccurdy** [comment]
Digging into the file a bit more, there are lots of junk keyframe tracks that aren't contributing anything to the final animation. Some are small (2 keyframes,  both identical) and others are large (50,627 keyframes, all containing `scale=1,1,1`). The `resample` command deals with the duplicate keyframes but doesn't currently prune no-op tracks. That — along with an automatic `dedup` step — would probably be reasonable additions to the function.

<img width="469" alt="Screen Shot 2022-02-16 at 11 03 06 AM" src="https://user-images.githubusercontent.com/1848368/154305910-f63a364a-7015-435f-b4f2-c54a618b3378.png">

**Comment by hybridherbst** [comment]
To chime in here regarding the file - everything with two keyframes is there because the "animation pose" is different to the "non-animated pose" for this model. The rest pose could be anything (e.g. stretched out) but if during the entire animation clip a part of the model would be rotated differently, then there's a start and end keyframe for that but no actual animation inbetween. So, these tracks aren't always "no-op tracks", they can also be "pose tracks" without any animation/movement happening.

**Comment by donmccurdy** [comment]
Somehow gltfpack manages to reduce this file to just 6 animation channels – I guess that must (at least in part) mean it's baking the animated pose to the rest pose? Does gltfpack's output work for your use cases, or is that something you'd want to be opt-in if it happens at all?

In either case, the track containing only `scale=1,1,1` could probably be removed by `resample()`... 😅

**Comment by kzhsw** [comment]
Manually set the `tolerance` to `1.1920928955078125e-7` (the epsilon for float32) would help.
```js
await document.transform(
	// Losslessly resample animation frames.
	resample({tolerance: 1.1920928955078125e-7}),

	// Remove duplicate vertex or texture data, if any.
	dedup(),

	// Remove unused nodes, textures, or other data.
	prune(),

);
```
[resampled.zip](https://github.com/donmccurdy/glTF-Transform/files/10297843/resampled.zip)

**Comment by donmccurdy** [comment]
This issue will be fixed in https://github.com/donmccurdy/glTF-Transform/pull/760. The main thing was using [slerp()](https://en.wikipedia.org/wiki/Slerp#:~:text=In%20computer%20graphics%2C%20Slerp%20is,purpose%20of%20animating%203D%20rotation.) to compare quaternion keyframes. I've left the two-keyframe "animation pose" channels alone, as I think removing those would probably be unexpected behavior for the resample() function here.
